Sonal Manandhar 2615878


> Add blockquote




#Part 1: Create and Understand Ndarray:
Ndarray object represents N-dimensional array. Ndarray has different properties/attributes,
which are useful information about the ndarray object.

Problem 1: Create a 2D ndarray of type Integer, e.g.,

1 2 3

4 5 6

7 8 9

and see its properties


Solution: To create any ndarray, we need to import the NumPy library and use the array()
function. Usually, the NumPy library is imported under the np alias (in Python alias are an
alternate name for referring to the same thing).

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
print("Array =")
print(arr)
print("Data Type of the Array                             =", arr.dtype)
print("Number of dimensions of the Array                  =", arr.ndim)
print("Shape of the Array                                 =", arr.shape)
print("Size of the Array                                  =", arr.size)
print("Number of bytes used by each element of the Array  =", arr.itemsize)
print("Total bytes used by the Array                      =", arr.nbytes)
print("Memory Layout information                          :\n", arr.flags)

Array =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Data Type of the Array                             = float64
Number of dimensions of the Array                  = 2
Shape of the Array                                 = (3, 3)
Size of the Array                                  = 9
Number of bytes used by each element of the Array  = 8
Total bytes used by the Array                      = 72
Memory Layout information                          :
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



Problem 2: Create a 2D ndarray (matrix) of shape (4,5) with all elements equal to 3.0 and print
the matrix.

In [ ]:
#Solution:

import numpy as np
arr2= 3.0*np.ones((4,5))
print("Array = ")
print(arr2)
print("Shape  = ",arr2.shape)
print("Datatype = ",arr2.dtype)

Array = 
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape  =  (4, 5)
Datatype =  float64


Problem 3: What is the other way to create the same matrix as above?

In [ ]:
#Solution
import numpy as np
arr3 = np.full((3, 3),3.0)
print("Matrix same as above = \n",arr3)

Matrix same as above = 
 [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


Problem 4: Construct a matrix [aij] of shape (3,3) whose elements are given by aij = 1/2 |𝑖 − 3𝑗|.



In [ ]:
#Solution
import numpy as np
arr4 = np.fromfunction(lambda i, j: np.abs(i+1-3*(j+1))/2, (3, 3), dtype=int)
print("Array = \n",arr4)
print("Shape = ",arr4.shape)
print("Datatype = ",arr4.dtype)

Array = 
 [[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape =  (3, 3)
Datatype =  float64


Problem 5: Construct a diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4].

In [ ]:
#Solution
import numpy as np
array5 = np.array([1,2,3,4])
print("Diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4] = \n",np.diag(array5))

Diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4] = 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Problem 6: Construct a matrix of shape (4,5) with whatever elements, and then slice it to obtain
a matrix of shape (3,3) that contains only upper-left portion of the original matrix.

In [ ]:
#Solution
import numpy as np
#Solution
import numpy as np
arr6 = np.fromfunction(lambda i, j: np.abs(i+1-3*(j+1))//2, (4, 5),dtype=int)
print("Random matrix of size (4,5) = \n",arr6)
print("\nSliced matrix of size (3,3) = \n",arr6[0:3,0:3])

Random matrix of size (4,5) = 
 [[1 2 4 5 7]
 [0 2 3 5 6]
 [0 1 3 4 6]
 [0 1 2 4 5]]

Sliced matrix of size (3,3) = 
 [[1 2 4]
 [0 2 3]
 [0 1 3]]


#Part 2: Perform some basic operation on Vectors/Matrices:

Problem 1: Create two matrices 𝑨 =

1 2 3

4 5 6

7 8 9

 and

𝑩 =

1 1 1

2 2 2

Add them together. What
do you observe? Give the explanation behind it.

In [ ]:
#Solution
import numpy as np
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2=np.array([[1,1,1],[2,2,2]])
array3 = array1 + array2
print(array3)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

Ans: We get an error trying to add the matrices. Two matrices of different shapes cannot be added so hence it shows an error

Problem 2: Given a matrix and a vector, write a Python function that performs Matrix-Vector
product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-
Matrix product.

In [ ]:
#Solution
import numpy as np
def dot_product(vec1, vec2):
    # flatten the input vectors
    vec1 = vec1.flatten()
    vec2 = vec2.flatten()
    return np.sum(np.multiply(vec1, vec2))

def matrix_vector_product(mat, vec):
    m, n = mat.shape
    p, q = vec.shape

    assert n == p, "the matrix and vector are not compatible for multiplication!"

    # create a ndarray to store the result
    result = np.zeros((m, q), dtype=float)

    # Loop to perform Matrix-Vector product
    # Perform dot product between the vector and each row of the matrix
    for i in range(m):
        result[i] = dot_product(mat[i, :], vec)

    return result

mat1 = np.full((3,3),3,dtype=int)
vec1 = np.full((3,1),2,dtype=int)
print("Matrix = ")
print(mat1)
print("Vector = ")
print(vec1)

result1 =  matrix_vector_product(mat1, vec1)
print("Matrix-Vector product = ")
print("Result = ")
print(result1)

result2 = mat1 @ vec1
print("Result = ")
print(result2)

Matrix = 
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector = 
[[2]
 [2]
 [2]]
Matrix-Vector product = 
Result = 
[[18.]
 [18.]
 [18.]]
Result = 
[[18]
 [18]
 [18]]


Problem 3: Given two compatible matrices, write a Python function that performs Matrix-Matrix
product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-
Matrix product.

In [ ]:
import numpy as np

def matrix_multiply(A, B):
    # Check if multiplication is possible
    if len(A[0]) != len(B):
        raise ValueError("Number of columns in A must equal number of rows in B")

    # Dimensions
    rows_A = len(A)
    cols_A = len(A[0])
    cols_B = len(B[0])

    # Initialize result matrix with zeros
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # Perform multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]
    return result

A = [[1, 2, 3],
    [4, 5, 6]]
B = [[7, 8],
    [9, 10],
    [11, 12]]

result = matrix_multiply(A, B)

print("Manual Result:")
for row in result:
    print(row)

A_np = np.array(A)
B_np = np.array(B)

numpy_result = np.dot(A_np, B_np)

print("\nNumPy Result:")
print(numpy_result)

v = [1, 2, 3]

# Convert to NumPy
v_np = np.array(v)

# Matrix-vector product
mv_result = np.dot(A_np, v_np)

print("\nMatrix-Vector Result (NumPy):")
print(mv_result)

Manual Result:
[58, 64]
[139, 154]

NumPy Result:
[[ 58  64]
 [139 154]]

Matrix-Vector Result (NumPy):
[14 32]


Problem 4: Given a matrix, write a Python function that checks if it is a symmetric matrix.

In [ ]:
import numpy as np

def is_symmetric(matrix):
    return np.array_equal(matrix, matrix.T)
a=[[1,2,3],
 [2,1,4],
 [3,4,1]]
a_np = np.array(a)
print(is_symmetric(a_np))


True
